# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\pleiades\workspace\mypyqt\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 568)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/vague.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(215, 227, 188);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 911, 531))
        self.tabWidget.setMinimumSize(QtCore.QSize(911, 501))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setStyleSheet("background-color: rgb(215, 227, 188);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(0, 0))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 491))
        self.groupBox.setObjectName("groupBox")
        self.fileView = QtWidgets.QTableWidget(self.groupBox)
        self.fileView.setGeometry(QtCore.QRect(10, 20, 391, 431))
        self.fileView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fileView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.fileView.setObjectName("fileView")
        self.fileView.setColumnCount(0)
        self.fileView.setRowCount(0)
        self.fileView.horizontalHeader().setStretchLastSection(True)
        self.preBtn = QtWidgets.QPushButton(self.groupBox)
        self.preBtn.setGeometry(QtCore.QRect(110, 460, 71, 23))
        self.preBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.preBtn.setObjectName("preBtn")
        self.addBtn = QtWidgets.QPushButton(self.groupBox)
        self.addBtn.setGeometry(QtCore.QRect(410, 30, 71, 23))
        self.addBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addBtn.setObjectName("addBtn")
        self.nextBtn = QtWidgets.QPushButton(self.groupBox)
        self.nextBtn.setGeometry(QtCore.QRect(190, 460, 71, 23))
        self.nextBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nextBtn.setObjectName("nextBtn")
        self.checkAllBtn = QtWidgets.QPushButton(self.groupBox)
        self.checkAllBtn.setGeometry(QtCore.QRect(410, 120, 71, 23))
        self.checkAllBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkAllBtn.setObjectName("checkAllBtn")
        self.removeBtn = QtWidgets.QPushButton(self.groupBox)
        self.removeBtn.setGeometry(QtCore.QRect(410, 60, 71, 23))
        self.removeBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.removeBtn.setObjectName("removeBtn")
        self.uncheckBtn = QtWidgets.QPushButton(self.groupBox)
        self.uncheckBtn.setGeometry(QtCore.QRect(410, 150, 71, 23))
        self.uncheckBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.uncheckBtn.setObjectName("uncheckBtn")
        self.clearAllBtn = QtWidgets.QPushButton(self.groupBox)
        self.clearAllBtn.setGeometry(QtCore.QRect(410, 180, 71, 23))
        self.clearAllBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.clearAllBtn.setObjectName("clearAllBtn")
        self.selectErrSb = QtWidgets.QSpinBox(self.groupBox)
        self.selectErrSb.setGeometry(QtCore.QRect(351, 460, 51, 22))
        self.selectErrSb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectErrSb.setObjectName("selectErrSb")
        self.selectBtn = QtWidgets.QPushButton(self.groupBox)
        self.selectBtn.setGeometry(QtCore.QRect(410, 460, 71, 23))
        self.selectBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectBtn.setObjectName("selectBtn")
        self.intersetBtn = QtWidgets.QPushButton(self.groupBox)
        self.intersetBtn.setGeometry(QtCore.QRect(410, 410, 71, 23))
        self.intersetBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.intersetBtn.setObjectName("intersetBtn")
        self.pagesizeSb = QtWidgets.QSpinBox(self.groupBox)
        self.pagesizeSb.setGeometry(QtCore.QRect(50, 460, 51, 22))
        self.pagesizeSb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pagesizeSb.setKeyboardTracking(False)
        self.pagesizeSb.setMaximum(1000)
        self.pagesizeSb.setProperty("value", 100)
        self.pagesizeSb.setObjectName("pagesizeSb")
        self.label_61 = QtWidgets.QLabel(self.groupBox)
        self.label_61.setGeometry(QtCore.QRect(10, 460, 31, 21))
        self.label_61.setObjectName("label_61")
        self.checkNum = QtWidgets.QLineEdit(self.groupBox)
        self.checkNum.setGeometry(QtCore.QRect(410, 250, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkNum.setFont(font)
        self.checkNum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkNum.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.checkNum.setMaxLength(4)
        self.checkNum.setAlignment(QtCore.Qt.AlignCenter)
        self.checkNum.setObjectName("checkNum")
        self.searchBtn = QtWidgets.QPushButton(self.groupBox)
        self.searchBtn.setGeometry(QtCore.QRect(410, 280, 71, 23))
        self.searchBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchBtn.setObjectName("searchBtn")
        self.onekeyGlBtn = QtWidgets.QPushButton(self.groupBox)
        self.onekeyGlBtn.setGeometry(QtCore.QRect(410, 310, 71, 23))
        self.onekeyGlBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.onekeyGlBtn.setObjectName("onekeyGlBtn")
        self.onekeyPcBtn = QtWidgets.QPushButton(self.groupBox)
        self.onekeyPcBtn.setGeometry(QtCore.QRect(410, 340, 71, 23))
        self.onekeyPcBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.onekeyPcBtn.setObjectName("onekeyPcBtn")
        self.allRemoveBtn = QtWidgets.QPushButton(self.groupBox)
        self.allRemoveBtn.setGeometry(QtCore.QRect(410, 90, 71, 23))
        self.allRemoveBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.allRemoveBtn.setObjectName("allRemoveBtn")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(520, 10, 381, 491))
        self.groupBox_11.setObjectName("groupBox_11")
        self.previewpte = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.previewpte.setGeometry(QtCore.QRect(10, 40, 361, 411))
        self.previewpte.setStyleSheet("")
        self.previewpte.setObjectName("previewpte")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 460, 51, 23))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.selectRevBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.selectRevBtn.setGeometry(QtCore.QRect(200, 460, 51, 23))
        self.selectRevBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectRevBtn.setObjectName("selectRevBtn")
        self.copybtn = QtWidgets.QPushButton(self.groupBox_11)
        self.copybtn.setGeometry(QtCore.QRect(260, 460, 51, 23))
        self.copybtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.copybtn.setObjectName("copybtn")
        self.saveBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.saveBtn.setGeometry(QtCore.QRect(320, 460, 51, 23))
        self.saveBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saveBtn.setObjectName("saveBtn")
        self.resultLb = QtWidgets.QLabel(self.groupBox_11)
        self.resultLb.setGeometry(QtCore.QRect(60, 10, 271, 21))
        self.resultLb.setText("")
        self.resultLb.setObjectName("resultLb")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(500, 10, 20, 481))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 881, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.t2_log_pte = QtWidgets.QTextBrowser(self.groupBox_2)
        self.t2_log_pte.setGeometry(QtCore.QRect(0, 110, 881, 331))
        self.t2_log_pte.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_log_pte.setObjectName("t2_log_pte")
        self.t2_qian_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_qian_sb.setGeometry(QtCore.QRect(40, 20, 121, 22))
        self.t2_qian_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_qian_sb.setProperty("value", 1)
        self.t2_qian_sb.setObjectName("t2_qian_sb")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 21, 20))
        self.label.setObjectName("label")
        self.t2_bai_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_bai_sb.setGeometry(QtCore.QRect(190, 20, 121, 22))
        self.t2_bai_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_bai_sb.setProperty("value", 2)
        self.t2_bai_sb.setObjectName("t2_bai_sb")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 21, 20))
        self.label_2.setObjectName("label_2")
        self.t2_shi_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_shi_sb.setGeometry(QtCore.QRect(340, 20, 121, 22))
        self.t2_shi_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_shi_sb.setProperty("value", 3)
        self.t2_shi_sb.setObjectName("t2_shi_sb")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 21, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(470, 20, 21, 20))
        self.label_4.setObjectName("label_4")
        self.t2_ge_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_ge_sb.setGeometry(QtCore.QRect(490, 20, 121, 22))
        self.t2_ge_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_ge_sb.setProperty("value", 4)
        self.t2_ge_sb.setObjectName("t2_ge_sb")
        self.t2_err_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_err_sb.setGeometry(QtCore.QRect(670, 20, 42, 22))
        self.t2_err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_err_sb.setProperty("value", 1)
        self.t2_err_sb.setObjectName("t2_err_sb")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(630, 20, 31, 20))
        self.label_5.setObjectName("label_5")
        self.t2_execute_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.t2_execute_btn.setGeometry(QtCore.QRect(780, 80, 75, 23))
        self.t2_execute_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_execute_btn.setObjectName("t2_execute_btn")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_12.setObjectName("label_12")
        self.t2_xuan_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_xuan_sb.setGeometry(QtCore.QRect(700, 50, 42, 22))
        self.t2_xuan_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_xuan_sb.setObjectName("t2_xuan_sb")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(680, 50, 16, 20))
        self.label_16.setObjectName("label_16")
        self.t2_r_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_r_sb.setGeometry(QtCore.QRect(770, 50, 42, 22))
        self.t2_r_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_r_sb.setObjectName("t2_r_sb")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(750, 50, 16, 20))
        self.label_17.setObjectName("label_17")
        self.t2_rb1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.t2_rb1.setGeometry(QtCore.QRect(730, 20, 61, 21))
        self.t2_rb1.setChecked(True)
        self.t2_rb1.setObjectName("t2_rb1")
        self.t2_rb2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.t2_rb2.setGeometry(QtCore.QRect(790, 20, 51, 21))
        self.t2_rb2.setObjectName("t2_rb2")
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setGeometry(QtCore.QRect(20, 50, 101, 20))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_2)
        self.label_53.setGeometry(QtCore.QRect(210, 50, 101, 20))
        self.label_53.setObjectName("label_53")
        self.t2_h2err_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_h2err_sb.setGeometry(QtCore.QRect(120, 50, 42, 22))
        self.t2_h2err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_h2err_sb.setProperty("value", 9)
        self.t2_h2err_sb.setObjectName("t2_h2err_sb")
        self.t2_h3err_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.t2_h3err_sb.setGeometry(QtCore.QRect(310, 50, 42, 22))
        self.t2_h3err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t2_h3err_sb.setProperty("value", 9)
        self.t2_h3err_sb.setObjectName("t2_h3err_sb")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.t3_rb1_2 = QtWidgets.QGroupBox(self.tab_3)
        self.t3_rb1_2.setGeometry(QtCore.QRect(10, 10, 891, 471))
        self.t3_rb1_2.setObjectName("t3_rb1_2")
        self.label_6 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_7.setGeometry(QtCore.QRect(460, 30, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_9.setGeometry(QtCore.QRect(460, 60, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_11.setGeometry(QtCore.QRect(460, 90, 31, 21))
        self.label_11.setObjectName("label_11")
        self.t3_ab_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_ab_sb.setGeometry(QtCore.QRect(40, 30, 401, 22))
        self.t3_ab_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_ab_sb.setProperty("value", 3)
        self.t3_ab_sb.setObjectName("t3_ab_sb")
        self.t3_ac_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_ac_sb.setGeometry(QtCore.QRect(480, 30, 401, 22))
        self.t3_ac_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_ac_sb.setProperty("value", 4)
        self.t3_ac_sb.setObjectName("t3_ac_sb")
        self.t3_ad_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_ad_sb.setGeometry(QtCore.QRect(40, 60, 401, 22))
        self.t3_ad_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_ad_sb.setProperty("value", 5)
        self.t3_ad_sb.setObjectName("t3_ad_sb")
        self.t3_bc_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_bc_sb.setGeometry(QtCore.QRect(480, 60, 401, 22))
        self.t3_bc_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_bc_sb.setProperty("value", 5)
        self.t3_bc_sb.setObjectName("t3_bc_sb")
        self.t3_bd_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_bd_sb.setGeometry(QtCore.QRect(40, 90, 401, 22))
        self.t3_bd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_bd_sb.setProperty("value", 6)
        self.t3_bd_sb.setObjectName("t3_bd_sb")
        self.t3_cd_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_cd_sb.setGeometry(QtCore.QRect(480, 90, 401, 22))
        self.t3_cd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_cd_sb.setProperty("value", 7)
        self.t3_cd_sb.setObjectName("t3_cd_sb")
        self.t3_log_pte = QtWidgets.QTextBrowser(self.t3_rb1_2)
        self.t3_log_pte.setGeometry(QtCore.QRect(10, 150, 881, 311))
        self.t3_log_pte.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_log_pte.setObjectName("t3_log_pte")
        self.t3_err_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_err_sb.setGeometry(QtCore.QRect(180, 120, 42, 22))
        self.t3_err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_err_sb.setProperty("value", 2)
        self.t3_err_sb.setObjectName("t3_err_sb")
        self.label_18 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_18.setGeometry(QtCore.QRect(140, 120, 31, 20))
        self.label_18.setObjectName("label_18")
        self.t3_execute_btn = QtWidgets.QPushButton(self.t3_rb1_2)
        self.t3_execute_btn.setGeometry(QtCore.QRect(810, 120, 75, 23))
        self.t3_execute_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_execute_btn.setObjectName("t3_execute_btn")
        self.label_13 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_13.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_13.setObjectName("label_13")
        self.t3_xuan_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_xuan_sb.setGeometry(QtCore.QRect(570, 120, 42, 22))
        self.t3_xuan_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_xuan_sb.setObjectName("t3_xuan_sb")
        self.label_36 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_36.setGeometry(QtCore.QRect(550, 120, 16, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_37.setGeometry(QtCore.QRect(620, 120, 16, 20))
        self.label_37.setObjectName("label_37")
        self.t3_r_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_r_sb.setGeometry(QtCore.QRect(640, 120, 42, 22))
        self.t3_r_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_r_sb.setObjectName("t3_r_sb")
        self.t3_rb1 = QtWidgets.QRadioButton(self.t3_rb1_2)
        self.t3_rb1.setGeometry(QtCore.QRect(700, 120, 61, 21))
        self.t3_rb1.setChecked(True)
        self.t3_rb1.setObjectName("t3_rb1")
        self.t3_rb2 = QtWidgets.QRadioButton(self.t3_rb1_2)
        self.t3_rb2.setGeometry(QtCore.QRect(760, 120, 51, 21))
        self.t3_rb2.setObjectName("t3_rb2")
        self.label_54 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_54.setGeometry(QtCore.QRect(230, 120, 111, 20))
        self.label_54.setObjectName("label_54")
        self.t3_h2err_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_h2err_sb.setGeometry(QtCore.QRect(330, 120, 42, 22))
        self.t3_h2err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_h2err_sb.setProperty("value", 18)
        self.t3_h2err_sb.setObjectName("t3_h2err_sb")
        self.t3_h3err_sb = QtWidgets.QSpinBox(self.t3_rb1_2)
        self.t3_h3err_sb.setGeometry(QtCore.QRect(480, 120, 42, 22))
        self.t3_h3err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t3_h3err_sb.setProperty("value", 18)
        self.t3_h3err_sb.setObjectName("t3_h3err_sb")
        self.label_55 = QtWidgets.QLabel(self.t3_rb1_2)
        self.label_55.setGeometry(QtCore.QRect(380, 120, 101, 20))
        self.label_55.setObjectName("label_55")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 891, 471))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(460, 30, 31, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 60, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(460, 60, 31, 21))
        self.label_22.setObjectName("label_22")
        self.t4_abc_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_abc_sb.setGeometry(QtCore.QRect(50, 30, 391, 22))
        self.t4_abc_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_abc_sb.setObjectName("t4_abc_sb")
        self.t4_abd_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_abd_sb.setGeometry(QtCore.QRect(490, 30, 391, 22))
        self.t4_abd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_abd_sb.setObjectName("t4_abd_sb")
        self.t4_acd_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_acd_sb.setGeometry(QtCore.QRect(50, 60, 391, 22))
        self.t4_acd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_acd_sb.setObjectName("t4_acd_sb")
        self.t4_bcd_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_bcd_sb.setGeometry(QtCore.QRect(490, 60, 391, 22))
        self.t4_bcd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_bcd_sb.setObjectName("t4_bcd_sb")
        self.t4_log_pte = QtWidgets.QTextBrowser(self.groupBox_4)
        self.t4_log_pte.setGeometry(QtCore.QRect(0, 120, 881, 341))
        self.t4_log_pte.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_log_pte.setObjectName("t4_log_pte")
        self.t4_err_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_err_sb.setGeometry(QtCore.QRect(490, 90, 42, 22))
        self.t4_err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_err_sb.setObjectName("t4_err_sb")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(450, 90, 31, 20))
        self.label_25.setObjectName("label_25")
        self.t4_execute_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.t4_execute_btn.setGeometry(QtCore.QRect(800, 90, 75, 23))
        self.t4_execute_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_execute_btn.setObjectName("t4_execute_btn")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_14.setObjectName("label_14")
        self.t4_rb2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.t4_rb2.setGeometry(QtCore.QRect(750, 90, 51, 21))
        self.t4_rb2.setObjectName("t4_rb2")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(540, 90, 16, 20))
        self.label_38.setObjectName("label_38")
        self.t4_xuan_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_xuan_sb.setGeometry(QtCore.QRect(560, 90, 42, 22))
        self.t4_xuan_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_xuan_sb.setObjectName("t4_xuan_sb")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(610, 90, 16, 20))
        self.label_39.setObjectName("label_39")
        self.t4_r_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.t4_r_sb.setGeometry(QtCore.QRect(630, 90, 42, 22))
        self.t4_r_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t4_r_sb.setObjectName("t4_r_sb")
        self.t4_rb1 = QtWidgets.QRadioButton(self.groupBox_4)
        self.t4_rb1.setGeometry(QtCore.QRect(690, 90, 61, 21))
        self.t4_rb1.setChecked(True)
        self.t4_rb1.setObjectName("t4_rb1")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 881, 461))
        self.groupBox_5.setObjectName("groupBox_5")
        self.t5_log_pte = QtWidgets.QTextBrowser(self.groupBox_5)
        self.t5_log_pte.setGeometry(QtCore.QRect(10, 260, 871, 201))
        self.t5_log_pte.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_log_pte.setObjectName("t5_log_pte")
        self.t5_qian_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_qian_sb.setGeometry(QtCore.QRect(40, 20, 131, 22))
        self.t5_qian_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_qian_sb.setObjectName("t5_qian_sb")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 21, 20))
        self.label_23.setObjectName("label_23")
        self.t5_bai_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_bai_sb.setGeometry(QtCore.QRect(200, 20, 131, 22))
        self.t5_bai_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_bai_sb.setObjectName("t5_bai_sb")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(180, 20, 21, 20))
        self.label_24.setObjectName("label_24")
        self.t5_shi_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_shi_sb.setGeometry(QtCore.QRect(360, 20, 121, 22))
        self.t5_shi_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_shi_sb.setObjectName("t5_shi_sb")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(340, 20, 21, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(490, 20, 21, 20))
        self.label_27.setObjectName("label_27")
        self.t5_ge_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_ge_sb.setGeometry(QtCore.QRect(510, 20, 111, 22))
        self.t5_ge_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_ge_sb.setObjectName("t5_ge_sb")
        self.t5_err_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_err_sb.setGeometry(QtCore.QRect(710, 20, 42, 22))
        self.t5_err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_err_sb.setObjectName("t5_err_sb")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(670, 20, 31, 20))
        self.label_28.setObjectName("label_28")
        self.t5_ad_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_ad_sb.setGeometry(QtCore.QRect(50, 110, 381, 22))
        self.t5_ad_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_ad_sb.setObjectName("t5_ad_sb")
        self.t5_bc_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_bc_sb.setGeometry(QtCore.QRect(50, 140, 381, 22))
        self.t5_bc_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_bc_sb.setObjectName("t5_bc_sb")
        self.t5_cd_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_cd_sb.setGeometry(QtCore.QRect(50, 200, 381, 22))
        self.t5_cd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_cd_sb.setObjectName("t5_cd_sb")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(20, 140, 31, 21))
        self.label_29.setObjectName("label_29")
        self.t5_h2err_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_h2err_sb.setGeometry(QtCore.QRect(390, 230, 42, 22))
        self.t5_h2err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_h2err_sb.setObjectName("t5_h2err_sb")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(20, 80, 31, 21))
        self.label_30.setObjectName("label_30")
        self.t5_bd_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_bd_sb.setGeometry(QtCore.QRect(50, 170, 381, 22))
        self.t5_bd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_bd_sb.setObjectName("t5_bd_sb")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(350, 230, 31, 20))
        self.label_31.setObjectName("label_31")
        self.t5_ac_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_ac_sb.setGeometry(QtCore.QRect(50, 80, 381, 22))
        self.t5_ac_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_ac_sb.setObjectName("t5_ac_sb")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(20, 50, 31, 21))
        self.label_32.setObjectName("label_32")
        self.t5_ab_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_ab_sb.setGeometry(QtCore.QRect(50, 50, 381, 22))
        self.t5_ab_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_ab_sb.setObjectName("t5_ab_sb")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(20, 200, 31, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(20, 110, 31, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(20, 170, 31, 21))
        self.label_35.setObjectName("label_35")
        self.label_65 = QtWidgets.QLabel(self.groupBox_5)
        self.label_65.setGeometry(QtCore.QRect(450, 80, 31, 21))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_5)
        self.label_66.setGeometry(QtCore.QRect(450, 110, 31, 16))
        self.label_66.setObjectName("label_66")
        self.t5_bcd_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_bcd_sb.setGeometry(QtCore.QRect(480, 140, 391, 22))
        self.t5_bcd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_bcd_sb.setObjectName("t5_bcd_sb")
        self.label_67 = QtWidgets.QLabel(self.groupBox_5)
        self.label_67.setGeometry(QtCore.QRect(450, 50, 31, 21))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_5)
        self.label_68.setGeometry(QtCore.QRect(450, 140, 31, 21))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_5)
        self.label_69.setGeometry(QtCore.QRect(790, 170, 31, 20))
        self.label_69.setObjectName("label_69")
        self.t5_abd_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_abd_sb.setGeometry(QtCore.QRect(480, 80, 391, 22))
        self.t5_abd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_abd_sb.setObjectName("t5_abd_sb")
        self.t5_acd_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_acd_sb.setGeometry(QtCore.QRect(480, 110, 391, 22))
        self.t5_acd_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_acd_sb.setObjectName("t5_acd_sb")
        self.t5_abc_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_abc_sb.setGeometry(QtCore.QRect(480, 50, 391, 22))
        self.t5_abc_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_abc_sb.setObjectName("t5_abc_sb")
        self.t5_h3err_sb = QtWidgets.QSpinBox(self.groupBox_5)
        self.t5_h3err_sb.setGeometry(QtCore.QRect(830, 170, 42, 22))
        self.t5_h3err_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_h3err_sb.setObjectName("t5_h3err_sb")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(10, 240, 61, 16))
        self.label_15.setObjectName("label_15")
        self.t5_execute_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.t5_execute_btn.setGeometry(QtCore.QRect(800, 230, 75, 23))
        self.t5_execute_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t5_execute_btn.setObjectName("t5_execute_btn")
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        self.label_40.setGeometry(QtCore.QRect(450, 170, 71, 21))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_5)
        self.label_41.setGeometry(QtCore.QRect(450, 190, 71, 21))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_5)
        self.label_42.setGeometry(QtCore.QRect(450, 210, 71, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_5)
        self.label_43.setGeometry(QtCore.QRect(450, 230, 71, 21))
        self.label_43.setObjectName("label_43")
        self.spinBox_36 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_36.setGeometry(QtCore.QRect(550, 170, 42, 22))
        self.spinBox_36.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_36.setObjectName("spinBox_36")
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setGeometry(QtCore.QRect(600, 170, 16, 20))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setGeometry(QtCore.QRect(530, 170, 16, 20))
        self.label_45.setObjectName("label_45")
        self.spinBox_37 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_37.setGeometry(QtCore.QRect(620, 170, 42, 22))
        self.spinBox_37.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_37.setObjectName("spinBox_37")
        self.spinBox_38 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_38.setGeometry(QtCore.QRect(550, 190, 42, 22))
        self.spinBox_38.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_38.setObjectName("spinBox_38")
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(600, 190, 16, 20))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_5)
        self.label_47.setGeometry(QtCore.QRect(530, 190, 16, 20))
        self.label_47.setObjectName("label_47")
        self.spinBox_39 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_39.setGeometry(QtCore.QRect(620, 190, 42, 22))
        self.spinBox_39.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_39.setObjectName("spinBox_39")
        self.spinBox_40 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_40.setGeometry(QtCore.QRect(550, 210, 42, 22))
        self.spinBox_40.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_40.setObjectName("spinBox_40")
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setGeometry(QtCore.QRect(600, 210, 16, 20))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setGeometry(QtCore.QRect(530, 210, 16, 20))
        self.label_49.setObjectName("label_49")
        self.spinBox_41 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_41.setGeometry(QtCore.QRect(620, 210, 42, 22))
        self.spinBox_41.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_41.setObjectName("spinBox_41")
        self.spinBox_42 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_42.setGeometry(QtCore.QRect(550, 230, 42, 22))
        self.spinBox_42.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_42.setObjectName("spinBox_42")
        self.label_50 = QtWidgets.QLabel(self.groupBox_5)
        self.label_50.setGeometry(QtCore.QRect(600, 230, 16, 20))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_5)
        self.label_51.setGeometry(QtCore.QRect(530, 230, 16, 20))
        self.label_51.setObjectName("label_51")
        self.spinBox_43 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_43.setGeometry(QtCore.QRect(620, 230, 42, 22))
        self.spinBox_43.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_43.setObjectName("spinBox_43")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 881, 491))
        self.groupBox_3.setObjectName("groupBox_3")
        self.t6_bai_sb = QtWidgets.QSpinBox(self.groupBox_3)
        self.t6_bai_sb.setGeometry(QtCore.QRect(100, 20, 31, 22))
        self.t6_bai_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t6_bai_sb.setProperty("value", 2)
        self.t6_bai_sb.setObjectName("t6_bai_sb")
        self.t6_shi_sb = QtWidgets.QSpinBox(self.groupBox_3)
        self.t6_shi_sb.setGeometry(QtCore.QRect(160, 20, 31, 22))
        self.t6_shi_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t6_shi_sb.setProperty("value", 3)
        self.t6_shi_sb.setObjectName("t6_shi_sb")
        self.label_56 = QtWidgets.QLabel(self.groupBox_3)
        self.label_56.setGeometry(QtCore.QRect(80, 20, 21, 20))
        self.label_56.setObjectName("label_56")
        self.t6_qian_sb = QtWidgets.QSpinBox(self.groupBox_3)
        self.t6_qian_sb.setGeometry(QtCore.QRect(40, 20, 31, 22))
        self.t6_qian_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t6_qian_sb.setProperty("value", 1)
        self.t6_qian_sb.setObjectName("t6_qian_sb")
        self.label_57 = QtWidgets.QLabel(self.groupBox_3)
        self.label_57.setGeometry(QtCore.QRect(140, 20, 21, 20))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_3)
        self.label_58.setGeometry(QtCore.QRect(20, 20, 21, 20))
        self.label_58.setObjectName("label_58")
        self.t6_ge_sb = QtWidgets.QSpinBox(self.groupBox_3)
        self.t6_ge_sb.setGeometry(QtCore.QRect(220, 20, 31, 22))
        self.t6_ge_sb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t6_ge_sb.setProperty("value", 4)
        self.t6_ge_sb.setObjectName("t6_ge_sb")
        self.label_59 = QtWidgets.QLabel(self.groupBox_3)
        self.label_59.setGeometry(QtCore.QRect(200, 20, 21, 20))
        self.label_59.setObjectName("label_59")
        self.t6_execute_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.t6_execute_btn.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.t6_execute_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t6_execute_btn.setObjectName("t6_execute_btn")
        self.t6_log_pte = QtWidgets.QTextBrowser(self.groupBox_3)
        self.t6_log_pte.setGeometry(QtCore.QRect(10, 80, 861, 411))
        self.t6_log_pte.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.t6_log_pte.setObjectName("t6_log_pte")
        self.label_60 = QtWidgets.QLabel(self.groupBox_3)
        self.label_60.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_60.setObjectName("label_60")
        self.t6_chknum_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.t6_chknum_le.setGeometry(QtCore.QRect(460, 20, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t6_chknum_le.setFont(font)
        self.t6_chknum_le.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.t6_chknum_le.setAlignment(QtCore.Qt.AlignCenter)
        self.t6_chknum_le.setObjectName("t6_chknum_le")
        self.label_62 = QtWidgets.QLabel(self.groupBox_3)
        self.label_62.setGeometry(QtCore.QRect(400, 22, 61, 20))
        self.label_62.setObjectName("label_62")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_63 = QtWidgets.QLabel(self.tab_7)
        self.label_63.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label_63.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_63.setObjectName("label_63")
        self.placele1 = QtWidgets.QLineEdit(self.tab_7)
        self.placele1.setGeometry(QtCore.QRect(40, 10, 261, 20))
        self.placele1.setMaxLength(50000)
        self.placele1.setObjectName("placele1")
        self.placele2 = QtWidgets.QLineEdit(self.tab_7)
        self.placele2.setGeometry(QtCore.QRect(40, 40, 261, 20))
        self.placele2.setMaxLength(50000)
        self.placele2.setObjectName("placele2")
        self.label_64 = QtWidgets.QLabel(self.tab_7)
        self.label_64.setGeometry(QtCore.QRect(10, 40, 31, 21))
        self.label_64.setObjectName("label_64")
        self.placele3 = QtWidgets.QLineEdit(self.tab_7)
        self.placele3.setGeometry(QtCore.QRect(40, 70, 261, 20))
        self.placele3.setMaxLength(50000)
        self.placele3.setObjectName("placele3")
        self.label_70 = QtWidgets.QLabel(self.tab_7)
        self.label_70.setGeometry(QtCore.QRect(10, 70, 31, 21))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.tab_7)
        self.label_71.setGeometry(QtCore.QRect(10, 100, 31, 21))
        self.label_71.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_71.setObjectName("label_71")
        self.placele4 = QtWidgets.QLineEdit(self.tab_7)
        self.placele4.setGeometry(QtCore.QRect(40, 100, 261, 20))
        self.placele4.setMaxLength(50000)
        self.placele4.setObjectName("placele4")
        self.label_72 = QtWidgets.QLabel(self.tab_7)
        self.label_72.setGeometry(QtCore.QRect(10, 130, 31, 21))
        self.label_72.setObjectName("label_72")
        self.placele5 = QtWidgets.QLineEdit(self.tab_7)
        self.placele5.setGeometry(QtCore.QRect(40, 130, 261, 20))
        self.placele5.setMaxLength(50000)
        self.placele5.setObjectName("placele5")
        self.label_73 = QtWidgets.QLabel(self.tab_7)
        self.label_73.setGeometry(QtCore.QRect(10, 160, 31, 21))
        self.label_73.setObjectName("label_73")
        self.placele6 = QtWidgets.QLineEdit(self.tab_7)
        self.placele6.setGeometry(QtCore.QRect(40, 160, 261, 20))
        self.placele6.setMaxLength(50000)
        self.placele6.setObjectName("placele6")
        self.label_74 = QtWidgets.QLabel(self.tab_7)
        self.label_74.setGeometry(QtCore.QRect(10, 190, 31, 21))
        self.label_74.setObjectName("label_74")
        self.placele7 = QtWidgets.QLineEdit(self.tab_7)
        self.placele7.setGeometry(QtCore.QRect(40, 190, 261, 20))
        self.placele7.setMaxLength(50000)
        self.placele7.setObjectName("placele7")
        self.label_75 = QtWidgets.QLabel(self.tab_7)
        self.label_75.setGeometry(QtCore.QRect(10, 220, 31, 21))
        self.label_75.setObjectName("label_75")
        self.placele8 = QtWidgets.QLineEdit(self.tab_7)
        self.placele8.setGeometry(QtCore.QRect(40, 220, 261, 20))
        self.placele8.setMaxLength(50000)
        self.placele8.setObjectName("placele8")
        self.label_76 = QtWidgets.QLabel(self.tab_7)
        self.label_76.setGeometry(QtCore.QRect(10, 250, 31, 21))
        self.label_76.setObjectName("label_76")
        self.placele9 = QtWidgets.QLineEdit(self.tab_7)
        self.placele9.setGeometry(QtCore.QRect(40, 250, 261, 20))
        self.placele9.setMaxLength(50000)
        self.placele9.setObjectName("placele9")
        self.label_77 = QtWidgets.QLabel(self.tab_7)
        self.label_77.setGeometry(QtCore.QRect(10, 280, 31, 21))
        self.label_77.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_77.setObjectName("label_77")
        self.placele10 = QtWidgets.QLineEdit(self.tab_7)
        self.placele10.setGeometry(QtCore.QRect(40, 280, 261, 20))
        self.placele10.setMaxLength(50000)
        self.placele10.setObjectName("placele10")
        self.label_78 = QtWidgets.QLabel(self.tab_7)
        self.label_78.setGeometry(QtCore.QRect(10, 310, 31, 21))
        self.label_78.setObjectName("label_78")
        self.placele11 = QtWidgets.QLineEdit(self.tab_7)
        self.placele11.setGeometry(QtCore.QRect(40, 310, 261, 20))
        self.placele11.setMaxLength(50000)
        self.placele11.setObjectName("placele11")
        self.label_79 = QtWidgets.QLabel(self.tab_7)
        self.label_79.setGeometry(QtCore.QRect(10, 340, 31, 21))
        self.label_79.setObjectName("label_79")
        self.placele12 = QtWidgets.QLineEdit(self.tab_7)
        self.placele12.setGeometry(QtCore.QRect(40, 340, 261, 20))
        self.placele12.setMaxLength(50000)
        self.placele12.setObjectName("placele12")
        self.label_80 = QtWidgets.QLabel(self.tab_7)
        self.label_80.setGeometry(QtCore.QRect(10, 370, 31, 21))
        self.label_80.setObjectName("label_80")
        self.placele13 = QtWidgets.QLineEdit(self.tab_7)
        self.placele13.setGeometry(QtCore.QRect(40, 370, 261, 20))
        self.placele13.setMaxLength(50000)
        self.placele13.setObjectName("placele13")
        self.label_81 = QtWidgets.QLabel(self.tab_7)
        self.label_81.setGeometry(QtCore.QRect(310, 100, 31, 21))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.tab_7)
        self.label_82.setGeometry(QtCore.QRect(310, 40, 31, 21))
        self.label_82.setObjectName("label_82")
        self.placele24 = QtWidgets.QLineEdit(self.tab_7)
        self.placele24.setGeometry(QtCore.QRect(340, 250, 261, 20))
        self.placele24.setMaxLength(50000)
        self.placele24.setObjectName("placele24")
        self.placele23 = QtWidgets.QLineEdit(self.tab_7)
        self.placele23.setGeometry(QtCore.QRect(340, 220, 261, 20))
        self.placele23.setMaxLength(50000)
        self.placele23.setObjectName("placele23")
        self.placele25 = QtWidgets.QLineEdit(self.tab_7)
        self.placele25.setGeometry(QtCore.QRect(340, 280, 261, 20))
        self.placele25.setMaxLength(50000)
        self.placele25.setObjectName("placele25")
        self.label_83 = QtWidgets.QLabel(self.tab_7)
        self.label_83.setGeometry(QtCore.QRect(10, 430, 31, 21))
        self.label_83.setObjectName("label_83")
        self.placele20 = QtWidgets.QLineEdit(self.tab_7)
        self.placele20.setGeometry(QtCore.QRect(340, 130, 261, 20))
        self.placele20.setMaxLength(50000)
        self.placele20.setObjectName("placele20")
        self.label_84 = QtWidgets.QLabel(self.tab_7)
        self.label_84.setGeometry(QtCore.QRect(310, 160, 31, 21))
        self.label_84.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.tab_7)
        self.label_85.setGeometry(QtCore.QRect(310, 250, 31, 21))
        self.label_85.setObjectName("label_85")
        self.placele21 = QtWidgets.QLineEdit(self.tab_7)
        self.placele21.setGeometry(QtCore.QRect(340, 160, 261, 20))
        self.placele21.setMaxLength(50000)
        self.placele21.setObjectName("placele21")
        self.label_86 = QtWidgets.QLabel(self.tab_7)
        self.label_86.setGeometry(QtCore.QRect(310, 220, 31, 21))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.tab_7)
        self.label_87.setGeometry(QtCore.QRect(310, 280, 31, 21))
        self.label_87.setObjectName("label_87")
        self.placele22 = QtWidgets.QLineEdit(self.tab_7)
        self.placele22.setGeometry(QtCore.QRect(340, 190, 261, 20))
        self.placele22.setMaxLength(50000)
        self.placele22.setObjectName("placele22")
        self.placele14 = QtWidgets.QLineEdit(self.tab_7)
        self.placele14.setGeometry(QtCore.QRect(40, 400, 261, 20))
        self.placele14.setMaxLength(50000)
        self.placele14.setObjectName("placele14")
        self.placele16 = QtWidgets.QLineEdit(self.tab_7)
        self.placele16.setGeometry(QtCore.QRect(340, 10, 261, 20))
        self.placele16.setMaxLength(50000)
        self.placele16.setObjectName("placele16")
        self.label_88 = QtWidgets.QLabel(self.tab_7)
        self.label_88.setGeometry(QtCore.QRect(310, 190, 31, 21))
        self.label_88.setObjectName("label_88")
        self.placele17 = QtWidgets.QLineEdit(self.tab_7)
        self.placele17.setGeometry(QtCore.QRect(340, 40, 261, 20))
        self.placele17.setMaxLength(50000)
        self.placele17.setObjectName("placele17")
        self.label_89 = QtWidgets.QLabel(self.tab_7)
        self.label_89.setGeometry(QtCore.QRect(310, 70, 31, 21))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.tab_7)
        self.label_90.setGeometry(QtCore.QRect(310, 130, 31, 21))
        self.label_90.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.tab_7)
        self.label_91.setGeometry(QtCore.QRect(10, 400, 31, 21))
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.tab_7)
        self.label_92.setGeometry(QtCore.QRect(310, 10, 31, 21))
        self.label_92.setObjectName("label_92")
        self.placele19 = QtWidgets.QLineEdit(self.tab_7)
        self.placele19.setGeometry(QtCore.QRect(340, 100, 261, 20))
        self.placele19.setMaxLength(50000)
        self.placele19.setObjectName("placele19")
        self.placele15 = QtWidgets.QLineEdit(self.tab_7)
        self.placele15.setGeometry(QtCore.QRect(40, 430, 261, 20))
        self.placele15.setMaxLength(50000)
        self.placele15.setObjectName("placele15")
        self.placele18 = QtWidgets.QLineEdit(self.tab_7)
        self.placele18.setGeometry(QtCore.QRect(340, 70, 261, 20))
        self.placele18.setMaxLength(50000)
        self.placele18.setObjectName("placele18")
        self.placele31 = QtWidgets.QLineEdit(self.tab_7)
        self.placele31.setGeometry(QtCore.QRect(640, 10, 261, 20))
        self.placele31.setMaxLength(50000)
        self.placele31.setObjectName("placele31")
        self.placele32 = QtWidgets.QLineEdit(self.tab_7)
        self.placele32.setGeometry(QtCore.QRect(640, 40, 261, 20))
        self.placele32.setMaxLength(50000)
        self.placele32.setObjectName("placele32")
        self.label_93 = QtWidgets.QLabel(self.tab_7)
        self.label_93.setGeometry(QtCore.QRect(310, 400, 31, 21))
        self.label_93.setObjectName("label_93")
        self.placele29 = QtWidgets.QLineEdit(self.tab_7)
        self.placele29.setGeometry(QtCore.QRect(340, 400, 261, 20))
        self.placele29.setMaxLength(50000)
        self.placele29.setObjectName("placele29")
        self.label_94 = QtWidgets.QLabel(self.tab_7)
        self.label_94.setGeometry(QtCore.QRect(310, 430, 31, 21))
        self.label_94.setObjectName("label_94")
        self.placele35 = QtWidgets.QLineEdit(self.tab_7)
        self.placele35.setGeometry(QtCore.QRect(640, 130, 261, 20))
        self.placele35.setMaxLength(50000)
        self.placele35.setObjectName("placele35")
        self.placele34 = QtWidgets.QLineEdit(self.tab_7)
        self.placele34.setGeometry(QtCore.QRect(640, 100, 261, 20))
        self.placele34.setMaxLength(50000)
        self.placele34.setObjectName("placele34")
        self.placele28 = QtWidgets.QLineEdit(self.tab_7)
        self.placele28.setGeometry(QtCore.QRect(340, 370, 261, 20))
        self.placele28.setMaxLength(50000)
        self.placele28.setObjectName("placele28")
        self.placele33 = QtWidgets.QLineEdit(self.tab_7)
        self.placele33.setGeometry(QtCore.QRect(640, 70, 261, 20))
        self.placele33.setMaxLength(50000)
        self.placele33.setObjectName("placele33")
        self.label_95 = QtWidgets.QLabel(self.tab_7)
        self.label_95.setGeometry(QtCore.QRect(310, 310, 31, 21))
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.tab_7)
        self.label_96.setGeometry(QtCore.QRect(310, 340, 31, 21))
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.tab_7)
        self.label_97.setGeometry(QtCore.QRect(610, 70, 31, 21))
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.tab_7)
        self.label_98.setGeometry(QtCore.QRect(610, 40, 31, 21))
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.tab_7)
        self.label_99.setGeometry(QtCore.QRect(610, 130, 31, 21))
        self.label_99.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_99.setObjectName("label_99")
        self.placele26 = QtWidgets.QLineEdit(self.tab_7)
        self.placele26.setGeometry(QtCore.QRect(340, 310, 261, 20))
        self.placele26.setMaxLength(50000)
        self.placele26.setObjectName("placele26")
        self.placele30 = QtWidgets.QLineEdit(self.tab_7)
        self.placele30.setGeometry(QtCore.QRect(340, 430, 261, 20))
        self.placele30.setMaxLength(50000)
        self.placele30.setObjectName("placele30")
        self.label_100 = QtWidgets.QLabel(self.tab_7)
        self.label_100.setGeometry(QtCore.QRect(610, 100, 31, 21))
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.tab_7)
        self.label_101.setGeometry(QtCore.QRect(310, 370, 31, 21))
        self.label_101.setObjectName("label_101")
        self.placele27 = QtWidgets.QLineEdit(self.tab_7)
        self.placele27.setGeometry(QtCore.QRect(340, 340, 261, 20))
        self.placele27.setMaxLength(50000)
        self.placele27.setObjectName("placele27")
        self.label_102 = QtWidgets.QLabel(self.tab_7)
        self.label_102.setGeometry(QtCore.QRect(610, 10, 31, 21))
        self.label_102.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_102.setObjectName("label_102")
        self.intersetBtn2 = QtWidgets.QPushButton(self.tab_7)
        self.intersetBtn2.setGeometry(QtCore.QRect(820, 160, 71, 23))
        self.intersetBtn2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.intersetBtn2.setObjectName("intersetBtn2")
        self.previewpte2 = QtWidgets.QLabel(self.tab_7)
        self.previewpte2.setGeometry(QtCore.QRect(620, 200, 271, 21))
        self.previewpte2.setText("")
        self.previewpte2.setObjectName("previewpte2")
        self.sub4btn = QtWidgets.QPushButton(self.tab_7)
        self.sub4btn.setGeometry(QtCore.QRect(640, 160, 75, 23))
        self.sub4btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub4btn.setObjectName("sub4btn")
        self.sub5btn = QtWidgets.QPushButton(self.tab_7)
        self.sub5btn.setGeometry(QtCore.QRect(730, 160, 75, 23))
        self.sub5btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub5btn.setObjectName("sub5btn")
        self.label_63.raise_()
        self.placele1.raise_()
        self.label_64.raise_()
        self.label_70.raise_()
        self.placele2.raise_()
        self.placele3.raise_()
        self.label_71.raise_()
        self.placele4.raise_()
        self.label_72.raise_()
        self.placele5.raise_()
        self.label_73.raise_()
        self.placele6.raise_()
        self.label_74.raise_()
        self.placele7.raise_()
        self.label_75.raise_()
        self.placele8.raise_()
        self.label_76.raise_()
        self.placele9.raise_()
        self.label_77.raise_()
        self.placele10.raise_()
        self.label_78.raise_()
        self.placele11.raise_()
        self.label_79.raise_()
        self.placele12.raise_()
        self.label_80.raise_()
        self.placele13.raise_()
        self.label_81.raise_()
        self.label_82.raise_()
        self.placele24.raise_()
        self.placele23.raise_()
        self.placele25.raise_()
        self.label_83.raise_()
        self.placele20.raise_()
        self.label_84.raise_()
        self.label_85.raise_()
        self.placele21.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.placele22.raise_()
        self.placele14.raise_()
        self.placele16.raise_()
        self.label_88.raise_()
        self.placele17.raise_()
        self.label_89.raise_()
        self.label_90.raise_()
        self.label_91.raise_()
        self.label_92.raise_()
        self.placele19.raise_()
        self.placele15.raise_()
        self.placele18.raise_()
        self.placele31.raise_()
        self.placele32.raise_()
        self.label_93.raise_()
        self.placele29.raise_()
        self.label_94.raise_()
        self.placele35.raise_()
        self.placele34.raise_()
        self.placele28.raise_()
        self.placele33.raise_()
        self.label_95.raise_()
        self.label_96.raise_()
        self.label_97.raise_()
        self.label_98.raise_()
        self.label_99.raise_()
        self.placele26.raise_()
        self.placele30.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.placele27.raise_()
        self.label_102.raise_()
        self.intersetBtn2.raise_()
        self.previewpte2.raise_()
        self.sub4btn.raise_()
        self.sub5btn.raise_()
        self.tabWidget.addTab(self.tab_7, "")
        self.folderbtn = QtWidgets.QPushButton(self.centralWidget)
        self.folderbtn.setEnabled(True)
        self.folderbtn.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.folderbtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.folderbtn.setObjectName("folderbtn")
        self.filePathLe = QtWidgets.QLineEdit(self.centralWidget)
        self.filePathLe.setGeometry(QtCore.QRect(90, 10, 801, 20))
        self.filePathLe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filePathLe.setObjectName("filePathLe")
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionAdd_files = QtWidgets.QAction(MainWindow)
        self.actionAdd_files.setObjectName("actionAdd_files")
        self.actionRemove_All_files = QtWidgets.QAction(MainWindow)
        self.actionRemove_All_files.setObjectName("actionRemove_All_files")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.removeBtn.clicked.connect(self.fileView.reset)
        self.removeBtn.clicked.connect(self.fileView.resizeRowsToContents)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "vague"))
        self.groupBox.setTitle(_translate("MainWindow", "文件集"))
        self.preBtn.setText(_translate("MainWindow", "上一批"))
        self.addBtn.setText(_translate("MainWindow", "添加"))
        self.nextBtn.setText(_translate("MainWindow", "下一批"))
        self.checkAllBtn.setText(_translate("MainWindow", "全选"))
        self.removeBtn.setText(_translate("MainWindow", "移除"))
        self.uncheckBtn.setText(_translate("MainWindow", "反选"))
        self.clearAllBtn.setText(_translate("MainWindow", "全清"))
        self.selectBtn.setText(_translate("MainWindow", "选择"))
        self.intersetBtn.setText(_translate("MainWindow", "交集"))
        self.label_61.setText(_translate("MainWindow", "条数："))
        self.searchBtn.setText(_translate("MainWindow", "查询"))
        self.onekeyGlBtn.setText(_translate("MainWindow", "一键隔连"))
        self.onekeyPcBtn.setText(_translate("MainWindow", "一键批次"))
        self.allRemoveBtn.setText(_translate("MainWindow", "全部移除"))
        self.groupBox_11.setTitle(_translate("MainWindow", "结果"))
        self.pushButton_9.setText(_translate("MainWindow", "恢复"))
        self.selectRevBtn.setText(_translate("MainWindow", "取反"))
        self.copybtn.setText(_translate("MainWindow", "复制"))
        self.saveBtn.setText(_translate("MainWindow", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "集合"))
        self.groupBox_2.setTitle(_translate("MainWindow", "条件"))
        self.label.setText(_translate("MainWindow", "千"))
        self.label_2.setText(_translate("MainWindow", "百"))
        self.label_3.setText(_translate("MainWindow", "十"))
        self.label_4.setText(_translate("MainWindow", "个"))
        self.label_5.setText(_translate("MainWindow", "容错"))
        self.t2_execute_btn.setText(_translate("MainWindow", "执行"))
        self.label_12.setText(_translate("MainWindow", "输出日志："))
        self.label_16.setText(_translate("MainWindow", "选"))
        self.label_17.setText(_translate("MainWindow", "容"))
        self.t2_rb1.setText(_translate("MainWindow", "123"))
        self.t2_rb2.setText(_translate("MainWindow", "45"))
        self.label_52.setText(_translate("MainWindow", "第一（2）步 容错"))
        self.label_53.setText(_translate("MainWindow", "第一（3）步 容错"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "第一步"))
        self.t3_rb1_2.setTitle(_translate("MainWindow", "条件"))
        self.label_6.setText(_translate("MainWindow", "AB:"))
        self.label_7.setText(_translate("MainWindow", "AC:"))
        self.label_8.setText(_translate("MainWindow", "AD:"))
        self.label_9.setText(_translate("MainWindow", "BC:"))
        self.label_10.setText(_translate("MainWindow", "BD:"))
        self.label_11.setText(_translate("MainWindow", "CD:"))
        self.label_18.setText(_translate("MainWindow", "容错"))
        self.t3_execute_btn.setText(_translate("MainWindow", "执行"))
        self.label_13.setText(_translate("MainWindow", "输出日志："))
        self.label_36.setText(_translate("MainWindow", "选"))
        self.label_37.setText(_translate("MainWindow", "容"))
        self.t3_rb1.setText(_translate("MainWindow", "123"))
        self.t3_rb2.setText(_translate("MainWindow", "45"))
        self.label_54.setText(_translate("MainWindow", "第二（2）步 容错"))
        self.label_55.setText(_translate("MainWindow", "第二（3）步 容错"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "第二步"))
        self.groupBox_4.setTitle(_translate("MainWindow", "条件"))
        self.label_19.setText(_translate("MainWindow", "ABC:"))
        self.label_20.setText(_translate("MainWindow", "ABD:"))
        self.label_21.setText(_translate("MainWindow", "ACD:"))
        self.label_22.setText(_translate("MainWindow", "BCD:"))
        self.label_25.setText(_translate("MainWindow", "容错"))
        self.t4_execute_btn.setText(_translate("MainWindow", "执行"))
        self.label_14.setText(_translate("MainWindow", "输出日志："))
        self.t4_rb2.setText(_translate("MainWindow", "45"))
        self.label_38.setText(_translate("MainWindow", "选"))
        self.label_39.setText(_translate("MainWindow", "容"))
        self.t4_rb1.setText(_translate("MainWindow", "123"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "第三步"))
        self.groupBox_5.setTitle(_translate("MainWindow", "条件"))
        self.label_23.setText(_translate("MainWindow", "千"))
        self.label_24.setText(_translate("MainWindow", "百"))
        self.label_26.setText(_translate("MainWindow", "十"))
        self.label_27.setText(_translate("MainWindow", "个"))
        self.label_28.setText(_translate("MainWindow", "容错"))
        self.label_29.setText(_translate("MainWindow", "BC:"))
        self.label_30.setText(_translate("MainWindow", "AC:"))
        self.label_31.setText(_translate("MainWindow", "容错"))
        self.label_32.setText(_translate("MainWindow", "AB:"))
        self.label_33.setText(_translate("MainWindow", "CD:"))
        self.label_34.setText(_translate("MainWindow", "AD:"))
        self.label_35.setText(_translate("MainWindow", "BD:"))
        self.label_65.setText(_translate("MainWindow", "ABD:"))
        self.label_66.setText(_translate("MainWindow", "ACD:"))
        self.label_67.setText(_translate("MainWindow", "ABC:"))
        self.label_68.setText(_translate("MainWindow", "BCD:"))
        self.label_69.setText(_translate("MainWindow", "容错"))
        self.label_15.setText(_translate("MainWindow", "输出日志："))
        self.t5_execute_btn.setText(_translate("MainWindow", "执行"))
        self.label_40.setText(_translate("MainWindow", "第四（1）步"))
        self.label_41.setText(_translate("MainWindow", "第四（2）步"))
        self.label_42.setText(_translate("MainWindow", "第四（3）步"))
        self.label_43.setText(_translate("MainWindow", "第四（4）步"))
        self.label_44.setText(_translate("MainWindow", "容"))
        self.label_45.setText(_translate("MainWindow", "选"))
        self.label_46.setText(_translate("MainWindow", "容"))
        self.label_47.setText(_translate("MainWindow", "选"))
        self.label_48.setText(_translate("MainWindow", "容"))
        self.label_49.setText(_translate("MainWindow", "选"))
        self.label_50.setText(_translate("MainWindow", "容"))
        self.label_51.setText(_translate("MainWindow", "选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "第四步"))
        self.groupBox_3.setTitle(_translate("MainWindow", "条件"))
        self.label_56.setText(_translate("MainWindow", "百"))
        self.label_57.setText(_translate("MainWindow", "十"))
        self.label_58.setText(_translate("MainWindow", "千"))
        self.label_59.setText(_translate("MainWindow", "个"))
        self.t6_execute_btn.setText(_translate("MainWindow", "一键生成"))
        self.label_60.setText(_translate("MainWindow", "输出日志："))
        self.label_62.setText(_translate("MainWindow", "校验号码："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "一键生成"))
        self.label_63.setText(_translate("MainWindow", "1234"))
        self.label_64.setText(_translate("MainWindow", "1235"))
        self.label_70.setText(_translate("MainWindow", "1236"))
        self.label_71.setText(_translate("MainWindow", "1237"))
        self.label_72.setText(_translate("MainWindow", "1245"))
        self.label_73.setText(_translate("MainWindow", "1246"))
        self.label_74.setText(_translate("MainWindow", "1247"))
        self.label_75.setText(_translate("MainWindow", "1256"))
        self.label_76.setText(_translate("MainWindow", "1257"))
        self.label_77.setText(_translate("MainWindow", "1267"))
        self.label_78.setText(_translate("MainWindow", "1345"))
        self.label_79.setText(_translate("MainWindow", "1346"))
        self.label_80.setText(_translate("MainWindow", "1347"))
        self.label_81.setText(_translate("MainWindow", "1467"))
        self.label_82.setText(_translate("MainWindow", "1456"))
        self.label_83.setText(_translate("MainWindow", "1357"))
        self.label_84.setText(_translate("MainWindow", "2345"))
        self.label_85.setText(_translate("MainWindow", "2356"))
        self.label_86.setText(_translate("MainWindow", "2347"))
        self.label_87.setText(_translate("MainWindow", "2357"))
        self.label_88.setText(_translate("MainWindow", "2346"))
        self.label_89.setText(_translate("MainWindow", "1457"))
        self.label_90.setText(_translate("MainWindow", "1567"))
        self.label_91.setText(_translate("MainWindow", "1356"))
        self.label_92.setText(_translate("MainWindow", "1367"))
        self.label_93.setText(_translate("MainWindow", "2467"))
        self.label_94.setText(_translate("MainWindow", "2567"))
        self.label_95.setText(_translate("MainWindow", "2367"))
        self.label_96.setText(_translate("MainWindow", "2456"))
        self.label_97.setText(_translate("MainWindow", "3467"))
        self.label_98.setText(_translate("MainWindow", "3457"))
        self.label_99.setText(_translate("MainWindow", "4567"))
        self.label_100.setText(_translate("MainWindow", "3567"))
        self.label_101.setText(_translate("MainWindow", "2457"))
        self.label_102.setText(_translate("MainWindow", "3456"))
        self.intersetBtn2.setText(_translate("MainWindow", "75交集"))
        self.sub4btn.setText(_translate("MainWindow", "截取4位"))
        self.sub5btn.setText(_translate("MainWindow", "截取5位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "7位连接"))
        self.folderbtn.setText(_translate("MainWindow", "选择导出目录"))
        self.filePathLe.setText(_translate("MainWindow", "E:\\test"))
        self.actionAdd_files.setText(_translate("MainWindow", "Add files..."))
        self.actionAdd_files.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionRemove_All_files.setText(_translate("MainWindow", "Remove All files"))
        self.actionRemove_All_files.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

